### ISSUE TITLE
DeprecationWarning when running tests for the sample-programs project

### ISSUE THREAD

**Issue by rzuckerm** [auroq/glotter#4]
## Describe the bug
I get a `DeprecationWarning` when running the tests for [sample-programs](https://github.com/TheRenegadeCoder/sample-programs) project.

## Code Snippet
A snippet of the integration code that is not functioning as expected.
This could be a test function, the module that calls `glotter.main`, or something else.

See [runner.py](https://github.com/TheRenegadeCoder/sample-programs/blob/main/runner.py)

### .glotter.yml
See [.glotter.yml](https://github.com/TheRenegadeCoder/sample-programs/blob/main/.glotter.yml)

### testinfo.yml
There are many, but here is the [Algol68 testinfo.yml](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/a/algol68/testinfo.yml)

**Stack Trace**
```
  <path-to>/sample-programs/venv/lib/python3.7/site-packages/docker/utils/utils.py:67: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s2 = StrictVersion(v2)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

## Expected behavior
I should not see the above warning.

## Screenshots
N/A

## Environment (please complete the following information):
- OS: Ubuntu 22.04
- Link to project (if public): [sample-programs](https://github.com/TheRenegadeCoder/sample-programs)
- Python Version: 3.7.16
- Glotter Version: 0.1.54

## Additional context
N/A

**Comment by rzuckerm** [comment]
Please assign me. I think I know how to fix this.

**Comment by rzuckerm** [comment]
This is going to be a lot more difficult than I first thought. Before changing anything, I cannot get the tests to run due to this error:
```console
(venv) $ pytest -vvl test
_____________________________________________________________________ ERROR collecting test/unit/test_testinfo.py _____________________________________________________________________
ImportError while importing test module '<path-to>/glotter/test/unit/test_testinfo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.7/site-packages/_pytest/python.py:501: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python3.7/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
venv/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:142: in exec_module
    exec(co, module.__dict__)
test/unit/test_testinfo.py:4: in <module>
    from glotter.testinfo import ContainerInfo, FolderInfo, TestInfo
glotter/__init__.py:2: in <module>
    from glotter.decorators import project_test, project_fixture
glotter/decorators.py:5: in <module>
    from glotter.source import get_sources
glotter/source.py:5: in <module>
    from glotter import testinfo
glotter/testinfo.py:2: in <module>
    from jinja2 import Environment, BaseLoader
venv/lib/python3.7/site-packages/jinja2/__init__.py:33: in <module>
    from jinja2.environment import Environment, Template
venv/lib/python3.7/site-packages/jinja2/environment.py:15: in <module>
    from jinja2 import nodes
venv/lib/python3.7/site-packages/jinja2/nodes.py:19: in <module>
    from jinja2.utils import Markup
venv/lib/python3.7/site-packages/jinja2/utils.py:642: in <module>
    from markupsafe import Markup, escape, soft_unicode
E   ImportError: cannot import name 'soft_unicode' from 'markupsafe' (<path-to>/glotter/venv/lib/python3.7/site-packages/markupsafe/__init__.py)
```
and if I try to use the glotter package tarball that I get from `rm -rf dist; python setup.py sdist` in the sample-programs project, I see a bunch of errors from pytest:
```console
(venv) $ ./samplerunner.sh test -l algol68
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/_pytest/main.py", line 193, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/_pytest/main.py", line 236, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/_pytest/main.py", line 246, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/_pytest/main.py", line 440, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "<path-to>/sample-programs/venv/lib/python3.7/site-packages/pluggy/manager.py", line 277, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_collection_modify_items' in plugin <glotter.test.TestCollectionPlugin object at 0x7f1f368a0e10>
```

**Comment by rzuckerm** [comment]
I figured the problem out. `pytest_collection_modify_items` should be `pytest_collection_modifyitems`. This is fixed in my fork, [glotter2](https://github.com/rzuckerm/glotter2).
